# Generated by Django 5.1.6 on 2025-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='English word')),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Noun'), ('adjective', 'Adjective'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('particle', 'Particle'), ('preposition', 'Preposition'), ('another', 'Another')], default='another', max_length=255, verbose_name='Part of speech')),
                ('transcription', models.CharField(blank=True, max_length=255, verbose_name='Transcription')),
                ('translation', models.CharField(max_length=255, verbose_name='Translation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
