# Generated by Django 5.1.6 on 2026-08-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='English word')),
                ('part_of_speech', models.CharField(choices=[('unknown', 'Unknown'), ('noun', 'Noun'), ('adjective', 'Adjective'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('particle', 'Particle'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('idiom', 'Idiom')], default='unknown', max_length=20, verbose_name='Part of speech')),
                ('transcription', models.CharField(blank=True, max_length=150, verbose_name='Transcription')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, max_length=512, null=True, verbose_name='Image URL')),
                ('difficulty_level', models.IntegerField(default=0, verbose_name='Difficulty level')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('word', 'part_of_speech'), name='unique_word_part_of_speech')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Translation variant')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
        ),
    ]
