# Generated by Django 5.1.6 on 2026-08-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_part_of_speech',
        ),
    ]
