# Generated by Django 5.1.6 on 2025-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun/Существительное'), ('adjective', 'Adjective'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('particle', 'Particle'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun'), ('another', 'Another')], default='another', max_length=255, verbose_name='Part of speech'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, verbose_name='English word'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'part_of_speech'), name='unique_word_part_of_speech'),
        ),
    ]
