# Generated by Django 5.1.6 on 2025-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_part_of_speech_alter_word_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun/Существительное'), ('adjective', 'Adjective/Прилагательное'), ('verb', 'Verb/Глагол'), ('adverb', 'Adverb/Наречие'), ('phrase', 'Phrase/Фраза'), ('particle', 'Particle/Частица'), ('preposition', 'Preposition/Предлог'), ('pronoun', 'Pronoun/Местоимение'), ('another', 'Another/Другое(Когда не знаешь)')], default='another', max_length=255, verbose_name='Part of speech'),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transcription'),
        ),
    ]
