# Generated by Django 5.1.6 on 2025-08-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_word_part_of_speech_alter_word_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='difficulty_level',
            field=models.IntegerField(default=0, verbose_name='Difficulty level'),
        ),
        migrations.AddField(
            model_name='word',
            name='image_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
