# Generated by Django 5.1.6 on 2026-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_word_difficulty_level_word_image_url_word_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('adjective', 'Adjective'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('phrase', 'Phrase'), ('particle', 'Particle'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun'), ('another', 'Another')], default='another', max_length=255, verbose_name='Part of speech'),
        ),
    ]
