# Generated by Django 5.1.6 on 2026-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0007_remove_word_translation_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug name'),
        ),
    ]
